<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ci [
  <!ELEMENT ci (task*,matrix*)>
  <!ELEMENT task (#PCDATA)>
  <!ATTLIST task id ID #REQUIRED>
  <!ELEMENT matrix (run*)>
  <!ATTLIST matrix id ID #REQUIRED>
  <!ELEMENT run (v*)>
  <!ATTLIST run matrix IDREF #IMPLIED>
  <!ATTLIST run task IDREF #IMPLIED>
  <!ELEMENT v (#PCDATA)>
  <!ATTLIST v n CDATA #REQUIRED>
]>
<ci>

  <task id="main"><![CDATA[
    sbt ++$scala package packageDoc &&
    sbt ++$scala helloworld/run helloworld/packageStage::run helloworld/fastOptStage::run helloworld/fullOptStage::run &&
    sbt 'set ScalaJSKeys.postLinkJSEnv in ScalaJSBuild.helloworld := new scala.scalajs.sbtplugin.env.phantomjs.PhantomJSEnv' \
        ++$scala helloworld/packageStage::run helloworld/fastOptStage::run helloworld/fullOptStage::run &&
    sbt ++$scala testingExample/test testingExample/packageStage::test testingExample/fastOptStage::test testingExample/fullOptStage::test &&
    sbt ++$scala testSuite/test testSuite/packageStage::test testSuite/fastOptStage::test testSuite/fullOptStage::test \
      noIrCheckTest/test noIrCheckTest/packageStage::test noIrCheckTest/fastOptStage::test noIrCheckTest/fullOptStage::test &&
    sbt 'set ScalaJSKeys.postLinkJSEnv in ScalaJSBuild.testSuite := new scala.scalajs.sbtplugin.env.phantomjs.PhantomJSEnv' \
        'set definedTests.in(ScalaJSBuild.testSuite, Test) ~= (_.filter(_.name != "scala.scalajs.test.compiler.IntTest"))' \
         ++$scala \
         testSuite/packageStage::test testSuite/fastOptStage::test testSuite/fullOptStage::test \
         noIrCheckTest/packageStage::test noIrCheckTest/fastOptStage::test noIrCheckTest/fullOptStage::test \
         testSuite/clean &&
    sbt 'set scalacOptions in ScalaJSBuild.testSuite += "-Xexperimental"' ++$scala testSuite/test testSuite/fastOptStage::test testSuite/fullOptStage::test &&
    sbt ++$scala compiler/test reversi/packageJS reversi/fullOptJS &&
    sh ci/checksizes.sh $scala &&
    sh ci/check-partest-coverage.sh $scala
  ]]></task>

  <task id="tools"><![CDATA[
    sbt ++$scala tools/package tools/test
  ]]></task>

  <task id="sbtplugin"><![CDATA[
    sbt ++$scala tools/package tools/test sbtPlugin/package sbtPlugin/test
  ]]></task>

  <task id="partestc"><![CDATA[
    sbt ++$scala partest/compile
  ]]></task>

  <task id="sbtplugin-test"><![CDATA[
    # Publish Scala.js artifacts locally
    sbt ++2.11.0 publishLocal ++2.10.4 tools/publishLocal sbtPlugin/publishLocal
    # Go into standalone project and test
    cd sbt-plugin-test
    sbt noDOM/run withDOM/run test
  ]]></task>

  <task id="partest-noopt"><![CDATA[
    sbt ++$scala package partestSuite/test
  ]]></task>

  <task id="partest-fastopt"><![CDATA[
    sbt ++$scala package "partestSuite/testOnly -- --fastOpt"
  ]]></task>

  <task id="partest-fullopt"><![CDATA[
    sbt ++$scala package "partestSuite/testOnly -- --fullOpt"
  ]]></task>

  <matrix id="pr">
    <run task="main">
      <v n="scala">2.10.2</v>
    </run>
    <run task="main">
      <v n="scala">2.10.3</v>
    </run>
    <run task="main">
      <v n="scala">2.10.4</v>
    </run>
    <run task="main">
      <v n="scala">2.11.0</v>
    </run>
    <run task="main">
      <v n="scala">2.11.1</v>
    </run>
    <run task="sbtplugin">
      <v n="scala">2.10.4</v>
    </run>
    <run task="tools">
      <v n="scala">2.11.0</v>
    </run>
    <run task="tools">
      <v n="scala">2.11.1</v>
    </run>
    <run task="partestc">
      <v n="scala">2.11.0</v>
    </run>
    <run task="partestc">
      <v n="scala">2.11.1</v>
    </run>
    <run task="sbtplugin-test" />
  </matrix>

  <matrix id="nightly">
    <run matrix="pr" />
    <run task="partest-noopt">
      <v n="scala">2.11.0</v>
    </run>
    <run task="partest-fastopt">
      <v n="scala">2.11.0</v>
    </run>
    <run task="partest-fullopt">
      <v n="scala">2.11.0</v>
    </run>
    <run task="partest-noopt">
      <v n="scala">2.11.1</v>
    </run>
    <run task="partest-fastopt">
      <v n="scala">2.11.1</v>
    </run>
    <run task="partest-fullopt">
      <v n="scala">2.11.1</v>
    </run>
  </matrix>

</ci>
